# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Source checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
       
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Build and publish to Apache Maven Central
      run: mvn -B deploy org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Norconex_commons-lang
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Site deploy - Install SSH Key
      uses: shimataro/ssh-key-action@v2.4.0
      with:
        key: ${{ secrets.SITE_SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.SITE_KNOWN_HOSTS }}
        if_key_exists: fail

    - name: Site deploy - Prepare Maven settings.xml
      uses: s4u/maven-settings-action@v2.8.0
      with:
        servers: |
          [{
            "id": "site-deployment",
            "username": "${{ secrets.SITE_USERNAME }}",
            "privateKey": "/home/runner/.ssh/id_rsa",
            "passphrase": "${{ secrets.SITE_PASSPHRASE }}",
            "directoryPermissions": 775,
            "filePermissions": 664
          }]
        properties: |
          [
            { "site.baseurl": "${{ secrets.SITE_BASE_URL }}" }
          ]

#    - name: cat settings.xml
#      run: cat ~/.m2/settings.xml

    - name: Site deploy - Publish
      run: mvn -B site:deploy
